- name: Install and configure Nexus Repository OSS (no roles)
  hosts: lab
  become: true
  tasks:

    - name: Install Nexus Repository OSS
      ansible.builtin.include_tasks:
        file: tasks/main.yml
      vars:
        #action: install
        #repository_url: "docker.io/sonatype/nexus3"
        # repository_tag can be a tag or a version. example: 1.15.0 or 1.15.0-beta1. default is 'latest'.
        # repository_tag: 1.14.8
        #repository_checksum: "80b945be128a6466320df09589d73ed4a5dbf09f3495243281d264bbc643228c"
        # repository_checksum_algorithm: "sha256"
        #repository_checksum_algorithm: "sha256"
        
        # data_dir : base folder to store data. example: "/data/vault" # default is /data/vault
        #data_dir: "/data/nexus"
        platform : "podman"