---

#########################################################
## Sonatype Nexus administration module                ##
#########################################################

# Validate global variables
- name: Validate required variables for Sonatype Nexus administration module...
  ansible.builtin.assert:
    that: "varitem is defined"
    fail_msg: "Required variable '{{ varitem }}' has not been provided."
    quiet: true
  loop_control:
    loop_var: varitem
  loop:
    - nexus_repository_id

#########################################################
## Get Nexus Repository variables from Vault           ##
#########################################################

# include task gather_nexus_repository_variables.yml
- name: Gather Nexus Repository variables...
  ansible.builtin.include_tasks: gather_nexus_repository_variables.yml

#########################################################
## Start                                               ##
#########################################################

- name: Start Nexus Repository...
  when: action == "start"
  block:

    # Show information message
    - name: Information message
      ansible.builtin.debug:
        msg: "This part is not (yet) implemented."

    # Stop playbook
    - name: Stop playbook
      ansible.builtin.meta: end_play

#########################################################
## Stop                                                ##
#########################################################

- name: Stop Nexus Repository...
  when: action == "stop"
  block:

    # Show information message
    - name: Information message
      ansible.builtin.debug:
        msg: "This part is not (yet) implemented."

    # Stop playbook
    - name: Stop playbook
      ansible.builtin.meta: end_play
