
#########################################################
## Sonatype Nexus administration module                ##
#########################################################

# include task gather_nexus_repository_variables.yml
- name: Gather Nexus Repository variables from the vault.
  ansible.builtin.include_tasks: gather_nexus_repository_variables.yml
  when:
    - vault_address is defined
    - vault_token is defined
    - nexus_repository_vault_name is defined
    - nexus_repository_server_name is defined

#########################################################
## Start                                               ##
#########################################################

- name: Start Nexus Repository service.
  when: action == 'start'
  block:

    # Show information message
    - name: Information message
      ansible.builtin.debug:
        msg: "This part is not (yet) implemented."

    # Stop playbook
    - name: Stop playbook
      ansible.builtin.meta: end_play

#########################################################
## Stop                                                ##
#########################################################

- name: Stop Nexus Repository...
  when: action == "stop"
  block:

    # Show information message
    - name: Information message
      ansible.builtin.debug:
        msg: "This part is not (yet) implemented."

    # Stop playbook
    - name: Stop playbook
      ansible.builtin.meta: end_play
