---

#########################################################
## Artifacts import module                             ##
#########################################################

# Show information
- name: "Import artifacts - Information message"
  ansible.builtin.debug:
    msg:
      - "Import artifact {{ item.path | basename }} ({{ (item.size | int / 1024 / 1024) | round(0) }}MB) to repository {{ nexus_repository_name }}. This may take a while..."

# Check if last character of nexus_repository_folder is a slash. If not, add it. nexus_repository_folder can also be empty.
- name: "Test if last character of nexus_repository_folder is a slash..."
  ansible.builtin.set_fact:
    nexus_repository_folder: "{{ nexus_repository_folder }}/"
  when: nexus_repository_folder | regex_search('/$') is not match and nexus_repository_folder != ""

# upload files to Nexus repository
- name: "Import artifacts to Nexus repository ({{ nexus_repository_address }})..."
  ansible.builtin.uri:
    url: "{{ nexus_repository_address }}/repository/{{ nexus_repository_name }}/{{ nexus_repository_folder }}{{ item.path | regex_replace('^' + source_folder | regex_escape, '') }}"
    method: PUT
    user: "{{ nexus_repository_username }}"
    password: "{{ nexus_repository_password }}"
    force_basic_auth: yes
    src: "{{ item.path }}"
    remote_src: true # use managed (remote) node
    status_code: 200, 201 # 201 Created, 200 OK
    validate_certs: "{{ nexus_repository_validate_certs | default(true) }}"
    headers:
      Content-Type: "application/octet-stream"
  register: upload_result
