---

#########################################################
## Vault module for nexus-repository                   ##
#########################################################
# secret engine name (vault_name): nexus-repository
# secret engine type: kv
# secret name: variable nexus_repository_vault_id, default '{{ ansible_fqdn | replace('.', '-') }}'

# Validate variables
- name: Validate required variables for action.
  ansible.builtin.assert:
    that: "item is defined"
    fail_msg: "Required variable '{{ item }}' has not been provided."
    quiet: true
  with_items:
    - vault_address
    - vault_token

# Register variable (_secret_engine_name)
- name: Register variable (secret_engine_name)...
  ansible.builtin.set_fact:
   _secret_engine_name: "{{ nexus_secret_engine_name | default('nexus-repository') }}"

# Register variable (_secret_name)
- name: Register variable (secret_name)...
  ansible.builtin.set_fact:
    _secret_name: "{{ nexus_vault_id | default( ansible_fqdn | replace('.', '-') ) }}"

#########################################################
## Secret Engine                                       ##
#########################################################

# Create secret_engine if it does not exist
- name: "Create Vault secret engine for {{ _secret_engine_name }}..."
  ansible.builtin.include_role:
    name: vault
    tasks_from: secret_engine.yml
  vars:
    action: create_secret_engine
    secret_engine_name: "{{ _secret_engine_name }}"
    secret_engine_description: "{{ nexus_secret_engine_description | default('Secrets for Sonatype Nexus Repository.') }}"
    secret_engine_type: "kv"

#########################################################
## Secrets                                             ##
#########################################################

# Declare variable _secret_keyvalue
- name: Register variable (secret_keyvalue)...
  ansible.builtin.set_fact:
    _secret_keyvalue: |
      admin_password: '{{ nexus_repository_password | default('change_me') }}'
      nexus_repository_url: '{{ nexus_repository_url | default('change_me') }}'
      nexus_repository_username: '{{ nexus_repository_username | default('change_me') }}'
      nexus_repository_password: '{{ nexus_repository_password | default('change_me') }}'
      nexus_repository_address: '{{ nexus_repository_address | default('change_me') }}'
      automation_username: '{{ automation_username | default('change_me') }}'
      automation_password: '{{ automation_password | default('change_me') }}'
      automation_email: '{{ automation_email | default('ansible@{{ ansible_fqdn }}') }}'

# Store usernames and passwords in Hashicorp Vault.
- name: Store secrets and configuration data in Vault...
  ansible.builtin.include_role:
    name: vault
    tasks_from: secrets.yml
  vars:
    action: create_secret
    secret_engine_name: "{{ _secret_engine_name }}"
    secret_name: "{{ _secret_name }}"
    secret_keyvalue: "{{ _secret_keyvalue | from_yaml }}"

# Create Vault policy for Nexus
# TODO

# Create Vault AppRole for Nexus
# TODO

# Generate RoleID and SecretID for Nexus
# TODO
