---

#########################################################
## Sonatype Nexus users module                         ##
#########################################################

# include task gather_nexus_repository_variables.yml
- name: Gather Nexus Repository variables...
  ansible.builtin.include_tasks: gather_nexus_repository_variables.yml
  when:
    - vault_address is defined
    - vault_token is defined
    - nexus_repository_vault_name is defined
    - nexus_repository_server_name is defined

#########################################################
## Get User                                            ##
#########################################################

- name: Get user
  when: action == "get_user"
  block:

    # Validate local variables
    - name: Validate local variables for Nexus Repository get_user action.
      ansible.builtin.assert:
        that: "{{ varitem }} is defined"
        fail_msg: "Required variable '{{ varitem }}' has not been provided."
        quiet: true
      loop_control:
        loop_var: varitem
      loop:
        - nexus_repository_address
        - nexus_repository_username
        - nexus_repository_password
        - nexus_username

    # Register var_result variable
    - name: Register var_result variable
      ansible.builtin.set_fact:
        var_result: "{{ var_result }}"
      no_log: true
      when: var_result is not defined

    # Show information message
    - name: This part is not (yet) implemented.
      ansible.builtin.debug:
        msg: "This part is not (yet) implemented."

    # Stop playbook
    - name: Stop playbook
      ansible.builtin.meta: end_play

#########################################################
## Create User                                         ##
#########################################################

- name: Create user
  when: action == "create_user"
  block:

    # Validate local variables
    - name: Validate local variables for Nexus Repository create_user action.
      ansible.builtin.assert:
        that: "{{ varitem }} is defined"
        fail_msg: "Required variable '{{ varitem }}' has not been provided."
        quiet: true
      loop_control:
        loop_var: varitem
      loop:
        - nexus_repository_address
        - nexus_repository_username
        - nexus_repository_password
        - nexus_repository_user_username
        - nexus_repository_user_password
        - nexus_repository_user_firstname
        - nexus_repository_user_lastname
        - nexus_repositiry_user_email
        - nexus_repository_user_roles

    # Create user in Nexus Repository Manager via API
    - name: Create User in Nexus Repository Manager
      ansible.builtin.uri:
        url: "{{ nexus_repository_address }}/service/rest/v1/security/users"
        method: POST
        user: "{{ nexus_repository_username }}"
        password: "{{ nexus_repository_password }}"
        force_basic_auth: yes
        body_format: json
        body:
          userId      : "{{ nexus_repository_user_username }}"
          firstName   : "{{ nexus_repository_user_firstname }}"
          lastName    : "{{ nexus_repository_user_lastname }}"
          emailAddress: "{{ nexus_repository_user_email }}"
          password    : "{{ nexus_repository_user_password }}"
          status      : "active"
          roles       : ["{{ nexus_repository_user_roles }}"]
        headers:
          accept: application/json
          Content-Type: application/json

#########################################################
## Destroy User                                        ##
#########################################################

- name: Destroy user on Nexus repository
  when: action == "destroy_user"
  block:

    # Validate local variables
    - name: Validate local variables for Nexus Repository destroy_user action.
      ansible.builtin.assert:
        that: "{{ varitem }} is defined"
        fail_msg: "Required variable '{{ varitem }}' has not been provided."
        quiet: true
      loop_control:
        loop_var: varitem
      loop:
        - nexus_repository_address
        - nexus_repository_username
        - nexus_repository_password
        - nexus_repository_user_username

    # Show information message
    - name: This part is not (yet) implemented.
      ansible.builtin.debug:
        msg: "This part is not (yet) implemented."

    # Stop playbook
    - name: Stop playbook
      ansible.builtin.meta: end_play

#########################################################
## Set password for user                               ##
#########################################################

- name: Destroy user on Nexus repository
  when: action == "set_password_user"
  block:

    # Validate local variables
    - name: Validate local variables for Nexus Repository set_password_user action.
      ansible.builtin.assert:
        that: "{{ varitem }} is defined"
        fail_msg: "Required variable '{{ varitem }}' has not been provided."
        quiet: true
      loop_control:
        loop_var: varitem
      loop:
        - nexus_repository_address
        - nexus_repository_username
        - nexus_repository_password
        - nexus_repository_user_username
        - nexus_repository_user_password

    # Show information message
    - name: This part is not (yet) implemented.
      ansible.builtin.debug:
        msg: "This part is not (yet) implemented."

    # Stop playbook
    - name: Stop playbook
      ansible.builtin.meta: end_play