---

- name: Export artifacts from Nexus Repository example
  hosts: localhost
  vars:
    vault_address: "{{ lookup('ansible.builtin.env', 'VAULT_ADDR', default=Undefined) }}"
    vault_token: "{{ lookup('ansible.builtin.env', 'VAULT_TOKEN', default=Undefined) }}"

  roles:
    # Export repository
    - role: nexus-repository
      vars:
        action : export_artifacts
        nexus_repository_id : "NXR-42M0002" # unique id to identify instance in Vault
        # nexus_repository_address : "" # Get from Vault
        # nexus_repository_username : "" # Get from Vault
        # nexus_repository_password : "" # Get from Vault
        nexus_repository_name : "files"
        nexus_repository_folder : "containers"
        destination_folder : "/tmp/demo"

  tasks:

    - name: Show information message
      debug:
        msg:
          - "Export completed from folder '{{ nexus_repository_folder }}' of '{{ nexus_repository_address }}'..."
          - "Destination folder: '{{ destination_folder }}'"
