---

# Example playbook to export artifacts from a Nexus Repository using Ansible

- name: Export artifacts from Nexus Repository example
  hosts: localhost
  vars:
    vault_address: "{{ lookup('ansible.builtin.env', 'VAULT_ADDR', default=Undefined) }}"
    vault_token: "{{ lookup('ansible.builtin.env', 'VAULT_TOKEN', default=Undefined) }}"

  roles:
    # Export repository
    - role: nexus-repository
      vars:
        action : export_artifacts
        nexus_repository_name : "files"
        nexus_repository_folder : "containers"
        destination_folder : "/tmp/demo"
        nexus_repository:
          # address:  # Get from Vault
          # username: # Get from Vault
          # password: # Get from Vault
          secrets:
            vault_id: "192-168-29-90" # unique id to identify instance in Vault

  tasks:

    - name: Show information message
      debug:
        msg:
          - "Export completed from folder '{{ nexus_repository_folder }}' of '{{ nexus_repository.address }}'..."
          - "Destination folder: '{{ destination_folder }}'"
