---

#########################################################
## Sonatype Nexus Repository artifacts sync            ##
#########################################################    
    
# Validate local variables
- name: Validate local variables for Nexus Repository sync_artifacts action.
  ansible.builtin.assert:
    that: "{{ varitem }} is defined"
    fail_msg: "Required variable '{{ varitem }}' has not been provided."
    quiet: true
  loop_control:
    loop_var: varitem
  loop:
    - nexus_repository_address
    - nexus_repository_username
    - nexus_repository_password

# Show information message
- name: This part is not (yet) implemented.
  ansible.builtin.debug:
    msg: "This part is not (yet) implemented."

# Stop playbook
- name: Stop playbook
  ansible.builtin.meta: end_play