---

#########################################################
## Sonatype Nexus repositories module                  ##
#########################################################

# include task gather_nexus_repository_variables.yml
- name: Gather Nexus Repository variables...
  ansible.builtin.include_tasks: gather_nexus_repository_variables.yml
  when:
    - vault_address is defined
    - vault_token is defined
    - nexus_repository_vault_id is defined

# Validate local variables
- name: Validate local variables for Nexus Repository get_repository action.
  ansible.builtin.assert:
    that: "varitem is defined"
    fail_msg: "Required variable '{{ varitem }}' has not been provided."
    quiet: true
  loop_control:
    loop_var: varitem
  loop:
    - nexus_repository_type

#########################################################
## RAW repository actions                              ##
#########################################################

# include task raw.yml for raw repository actions
- name: Include raw repository actions...
  ansible.builtin.include_tasks: raw.yml
  when:
    - nexus_repository_type == "raw"

#########################################################
## YUM repository actions                              ##
#########################################################

# include task yum.yml for raw repository actions
- name: Include yum repository actions...
  ansible.builtin.include_tasks: yum.yml
  when:
    - nexus_repository_type == "yum"

#########################################################
## YUM_PROXY repository actions                        ##
#########################################################

# include task yum.yml for raw repository actions
- name: Include yum repository actions...
  ansible.builtin.include_tasks: yum_proxy.yml
  when:
    - nexus_repository_type == "yum_proxy"

#########################################################
## Docker repository actions                           ##
#########################################################

# include task docker.yml for raw repository actions
- name: Include docker repository actions...
  ansible.builtin.include_tasks: docker.yml
  when:
    - nexus_repository_type == "docker"
